.TH NELMA-DRC 1 2006-12-10 "Tomaz Solc" "Nelma User's Manual"
.SH NAME
nelma-drc \- Designer rule checker for Nelma tools
.SH SYNOPSIS
.B nelma-drc
.I layer.png
.SH DESCRIPTION
.B nelma-drc
will check layer masks for any errors that could affect the accuracy of numerical calculations performed by Nelma tools. 
.P
A list of DRC errors and a summary is printed to standard output. Other messages are sent to standard error.
.SH AUTHOR
Tomaz Solc (tomaz.solc@tablix.org)
.SH SEE ALSO
.BR nelma-drc (1)
